# Generated by Django 3.0.2 on 2020-01-13 02:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proximoslancamento_mission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proximoslancamento',
            name='mission_id',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6),
        ),
    ]
