# Generated by Django 3.0.2 on 2020-01-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200112_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proximoslancamento',
            name='mission_id',
            field=models.CharField(max_length=150),
        ),
    ]
