# Generated by Django 3.0.2 on 2020-01-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200112_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='proximoslancamento',
            name='launch_date_local',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proximoslancamento',
            name='launch_year',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proximoslancamento',
            name='rocket',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
