# Generated by Django 3.0.2 on 2020-01-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200113_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proximoslancamento',
            old_name='rocket',
            new_name='details',
        ),
        migrations.AddField(
            model_name='proximoslancamento',
            name='is_tentative',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proximoslancamento',
            name='launch_date_unix',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proximoslancamento',
            name='launch_window',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proximoslancamento',
            name='tbd',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proximoslancamento',
            name='tentative_max_precision',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
