# Generated by Django 3.0.2 on 2020-01-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200113_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='proximoslancamento',
            name='launch_date_utc',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
