# Generated by Django 3.0.2 on 2020-01-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_proximoslancamento_launch_date_utc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentosPassado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=150)),
                ('mission_name', models.CharField(max_length=150)),
                ('launch_year', models.CharField(max_length=150)),
                ('launch_date_unix', models.CharField(max_length=150)),
                ('launch_date_utc', models.CharField(max_length=150)),
                ('launch_date_local', models.CharField(max_length=150)),
                ('is_tentative', models.CharField(max_length=150)),
                ('tentative_max_precision', models.CharField(max_length=150)),
                ('tbd', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=150)),
            ],
        ),
    ]
